### ISSUE TITLE
Versioning "title" had written wrong in last release.

### ISSUE THREAD

**Issue by Mirivhbv** [kannansuresh/jekyll-blog-archive-workflow#1]
Hi,

Till version number 1.0.3, you have used convention as "v1.0.2", but your latest version is "1.0.2" without "v". So please, create new release as "v1.0.3" or modify "@v1.0.3" to "@1.0.3" in samples you provide.

Anyway, thank you for this action 👍

**Comment by kannansuresh** [comment]
Could you please check if this is fixed now?

**Comment by Mirivhbv** [comment]
Yes, it works now. Thank you.
