### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by griggril000** [kannansuresh/jekyll-blog-archive-workflow#6]
I'm getting a json error I don't know how to fix. I tried following all the instructions, but I get this output during the action build:
`JSON Error. Check input variable archive_url. Passed variable [(my website url).](my website url) Expecting value: line 1 column 1 (char 0)`

How do I resolve this? Note: I replaced the url the console wrote with (my website url) for privacy.

**Comment by kannansuresh** [comment]
At which stage are you encountering this challenge? Is the error appearing when you execute the GitHub action? It appears that this may be related to some configuration within your site.

**Comment by griggril000** [comment]
It is appearing when I execute the action, yes.

**Comment by griggril000** [comment]
I found another piece of code that works. Thank you!
